# Generated by Django 3.0.6 on 2020-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
