# Generated by Django 3.0.6 on 2020-06-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfs_app', '0003_auto_20200605_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
